package org.backendcompas.modules.ai.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import org.backendcompas.modules.ai.model.ChatMessage;
import org.backendcompas.modules.ai.model.ChatRole;

import java.time.Instant;
import java.util.UUID;

@Schema(
        name = "ChatMessage",
        description = """
                A single message in the student's conversation history with the AI coach.

                Messages are returned **newest first** (descending `createdAt`) from
                `GET /api/v1/ai/chat/history`. Each exchange produces two entries: one with
                `role = USER` (the student's message) and one with `role = ASSISTANT` (the AI reply),
                both sharing the same logical turn.
                """
)
public record ChatMessageDto(

        @Schema(
                description = "Unique UUID of this message record.",
                example = "9f6c0c59-8e42-4d55-9f40-8c1f7b4e9b34"
        )
        UUID id,

        @Schema(
                description = """
                        Who authored this message:
                        - `USER` — sent by the student
                        - `ASSISTANT` — generated by the AI coach
                        """,
                example = "ASSISTANT",
                allowableValues = {"USER", "ASSISTANT"}
        )
        ChatRole role,

        @Schema(
                description = "Full text content of the message.",
                example = "Based on your profile you have 315 RON allocated for food this month."
        )
        String content,

        @Schema(
                description = "UTC timestamp when this message was persisted.",
                example = "2026-05-16T11:30:05Z"
        )
        Instant createdAt
) {
    public static ChatMessageDto from(ChatMessage msg) {
        return new ChatMessageDto(msg.getId(), msg.getRole(), msg.getContent(), msg.getCreatedAt());
    }
}
