package org.backendcompas.modules.recommendations.controller;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import org.backendcompas.core.exception.ApiError;
import org.backendcompas.core.exception.BadRequestException;
import org.backendcompas.core.exception.UnauthorizedException;
import org.backendcompas.core.security.CustomUserDetails;
import org.backendcompas.modules.recommendations.dto.AiRecommendationResponseDto;
import org.backendcompas.modules.recommendations.service.AiRecommendationService;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@Tag(
        name = "Recommendations",
        description = """
                AI-powered, budget-aware product recommendations for authenticated students.

                This endpoint enriches the request with the student's lifestyle profile and their
                real-time remaining budget for the requested category before forwarding it to the
                internal Python/FastAPI LLM orchestration service. The AI layer uses this context
                to surface items that are both personally relevant and affordable within the
                student's remaining monthly allocation.

                Results are cached per `(userId, category)` pair to minimise downstream latency.
                The internal Python service is protected with the `X-Internal-Secret` header and
                strict network timeouts (connect 3 s, read 15 s).
                """
)
@RestController
@RequiredArgsConstructor
@RequestMapping(value = "/api/v1/recommendations", produces = MediaType.APPLICATION_JSON_VALUE)
public class RecommendationController {

    /**
     * Valid category values accepted by the budget module. Kept here as a guard so the controller
     * rejects obviously invalid strings before touching the service layer or the cache.
     * Extend this set when new budget categories are added.
     */
    private static final java.util.Set<String> VALID_CATEGORIES = java.util.Set.of(
            "FOOD", "TRANSPORT", "ENTERTAINMENT", "HEALTH", "CLOTHING",
            "EDUCATION", "UTILITIES", "PERSONAL_CARE", "SAVINGS", "OTHER"
    );

    private final AiRecommendationService aiRecommendationService;

    @Operation(
            summary = "Get context-aware AI recommendations for a spending category",
            description = """
                    Returns a cached, personalised recommendation list generated by the internal
                    Python/FastAPI AI service.

                    **Request enrichment pipeline (Spring Boot → FastAPI):**
                    1. Extracts the caller's UUID from the JWT-backed `SecurityContext`.
                    2. Loads the student's `StudentProfile` (onboarding signals: living area, eating
                       habit, home package frequency). Returns **404** if onboarding is incomplete.
                    3. Loads the current month's `MonthlyBudget` and resolves the `remainingBudget`
                       for the requested `category` (`allocated_amount − spent_amount`, clamped ≥ 0).
                       If no budget or category entry exists, `remainingBudget` is sent as `0.00`.
                    4. Sends an enriched `POST {ai.service.url}/api/v1/recommendations` payload to
                       the Python microservice and returns its ranked recommendation list.

                    **Caching**: responses are cached under the key `{userId}_{CATEGORY}`.
                    A cache miss triggers a live call to the AI microservice; a hit returns instantly.

                    **Category validation**: the `category` parameter is case-insensitive but must
                    match a known budget category name (e.g. `FOOD`, `TRANSPORT`). Invalid values
                    are rejected with **400** before any I/O occurs.
                    """,
            security = @SecurityRequirement(name = "BearerAuth")
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "200",
                    description = "Recommendations returned successfully (may be served from cache).",
                    content = @Content(
                            mediaType = MediaType.APPLICATION_JSON_VALUE,
                            schema = @Schema(implementation = AiRecommendationResponseDto.class),
                            examples = @ExampleObject(
                                    name = "LLM recommendations for FOOD",
                                    value = """
                                            {
                                              "userId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
                                              "source": "llm",
                                              "recommendations": [
                                                {
                                                  "productId": "partner-kaufland-rice-1kg",
                                                  "name": "Rice 1kg",
                                                  "price": 9.50,
                                                  "category": "Groceries",
                                                  "storeName": "Kaufland",
                                                  "isPartner": true,
                                                  "reason": "Low-cost staple that fits your FOOD budget of 120.50 RON and covers several meals this week."
                                                },
                                                {
                                                  "productId": "partner-lidl-pasta-500g",
                                                  "name": "Pasta 500g",
                                                  "price": 4.99,
                                                  "category": "Groceries",
                                                  "storeName": "Lidl",
                                                  "isPartner": false,
                                                  "reason": "High-energy meal base ideal for dorm cooking on a tight weekly budget."
                                                }
                                              ]
                                            }
                                            """
                            )
                    )
            ),
            @ApiResponse(
                    responseCode = "400",
                    description = """
                            Bad request. Occurs when:
                            - `category` query parameter is missing or blank.
                            - `category` does not match any recognised budget category name.

                            Valid values: `FOOD`, `TRANSPORT`, `ENTERTAINMENT`, `HEALTH`, `CLOTHING`,
                            `EDUCATION`, `UTILITIES`, `PERSONAL_CARE`, `SAVINGS`, `OTHER`.
                            """,
                    content = @Content(
                            mediaType = MediaType.APPLICATION_JSON_VALUE,
                            schema = @Schema(implementation = ApiError.class),
                            examples = @ExampleObject(
                                    name = "Unknown category",
                                    value = """
                                            {
                                              "status": 400,
                                              "error": "Bad Request",
                                              "message": "Unknown budget category: 'GROCERIES'. Valid values: FOOD, TRANSPORT, ENTERTAINMENT, HEALTH, CLOTHING, EDUCATION, UTILITIES, PERSONAL_CARE, SAVINGS, OTHER",
                                              "path": "/api/v1/recommendations",
                                              "timestamp": "2026-05-17T09:00:00Z"
                                            }
                                            """
                            )
                    )
            ),
            @ApiResponse(
                    responseCode = "401",
                    description = "Missing or invalid JWT access token.",
                    content = @Content(mediaType = MediaType.APPLICATION_JSON_VALUE,
                            schema = @Schema(implementation = ApiError.class))
            ),
            @ApiResponse(
                    responseCode = "404",
                    description = """
                            The authenticated student has not completed onboarding — no `StudentProfile`
                            record exists. Direct the user to complete the onboarding flow before
                            requesting recommendations.
                            """,
                    content = @Content(
                            mediaType = MediaType.APPLICATION_JSON_VALUE,
                            schema = @Schema(implementation = ApiError.class),
                            examples = @ExampleObject(
                                    name = "Onboarding incomplete",
                                    value = """
                                            {
                                              "status": 404,
                                              "error": "Not Found",
                                              "message": "Student profile not found. Please complete onboarding before requesting recommendations.",
                                              "path": "/api/v1/recommendations",
                                              "timestamp": "2026-05-17T09:00:00Z"
                                            }
                                            """
                            )
                    )
            ),
            @ApiResponse(
                    responseCode = "503",
                    description = "AI service is temporarily unavailable or returned an upstream 4xx/5xx error.",
                    content = @Content(mediaType = MediaType.APPLICATION_JSON_VALUE,
                            schema = @Schema(implementation = ApiError.class))
            ),
            @ApiResponse(
                    responseCode = "504",
                    description = "AI service timed out within the configured 15-second read window.",
                    content = @Content(mediaType = MediaType.APPLICATION_JSON_VALUE,
                            schema = @Schema(implementation = ApiError.class))
            )
    })
    @GetMapping
    public ResponseEntity<AiRecommendationResponseDto> getRecommendations(
            @AuthenticationPrincipal CustomUserDetails userDetails,

            @Parameter(
                    name = "category",
                    description = """
                            Budget category for which to generate recommendations.
                            Case-insensitive — `food`, `FOOD`, and `Food` are all accepted.
                            Must match one of the recognised category names.
                            """,
                    example = "FOOD",
                    required = true
            )
            @RequestParam(value = "category") String category,

            @Parameter(
                    name = "userNote",
                    description = """
                            Optional free-text preference hint from the student
                            (e.g. `I want vegan options only`, `gluten-free please`).
                            Forwarded verbatim to the AI service to steer the LLM output.
                            Max 500 characters. Omit entirely or leave blank to apply no hint.
                            """,
                    example = "I want vegan options only",
                    required = false
            )
            @RequestParam(value = "userNote", required = false) String userNote
    ) {
        if (userDetails == null) {
            throw new UnauthorizedException("Authentication is required");
        }

        String normalised = category.trim().toUpperCase();
        if (normalised.isBlank()) {
            throw new BadRequestException("category must not be blank");
        }
        if (!VALID_CATEGORIES.contains(normalised)) {
            throw new BadRequestException(
                    "Unknown budget category: '" + category + "'. Valid values: " +
                    String.join(", ", new java.util.TreeSet<>(VALID_CATEGORIES)));
        }

        return ResponseEntity.ok(
                aiRecommendationService.getContextualRecommendations(userDetails.getUserId(), normalised, userNote));
    }
}
